apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebuy-db2
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: ebuy-db2
spec:
  selector:
    matchLabels:
      app: ebuy-db2
      deployment: ebuy-db2
  replicas: 1
  template:
    metadata:
      labels:
        app: ebuy-db2
        deployment: ebuy-db2
    spec:
      imagePullSecrets:
        - name: hyc-secret
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: ebuy-db2
          env:
            - name: DB2INST1_PASSWORD
              value: db2inst1
            - name: LICENSE
              value: accept
            - name: APP
              value: ebuy
          securityContext:
            capabilities:
            privileged: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 50000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: docker-na-public.artifactory.swg-devops.com/hyc-wassvt-team-image-registry-docker-local/db2/svt-db2:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: mysvcacct
      serviceAccount: mysvcacct
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
