kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: ebuy-db2
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: ebuy-db2
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: ebuy-db2
    deploymentconfig: ebuy-db2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ebuy-db2
        deploymentconfig: ebuy-db2
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: ebuy-db2
          env:
            - name: DB2INST1_PASSWORD
              value: db2inst1
            - name: LICENSE
              value: accept
            - name: APP
              value: ebuy
          securityContext:
            capabilities:
            privileged: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 50000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: hyc-wassvt-team-image-registry-docker-local.artifactory.swg-devops.com/db2/svt-db2:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: mysvcacct
      serviceAccount: mysvcacct
      schedulerName: default-scheduler
