apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:cap-cr-scc
  annotations:
    argocd.argoproj.io/sync-wave: "5"
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - cap-cr-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
